# Generated by Django 4.0.3 on 2022-03-31 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Number', models.CharField(max_length=30)),
                ('Operating_Airlines', models.CharField(max_length=30)),
                ('Departure_City', models.CharField(max_length=30)),
                ('Arrival_City', models.CharField(max_length=30)),
                ('Date_of_Departure', models.DateField()),
                ('Time_of_Onboard', models.TimeField()),
                ('Time_of_Offboard', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passenger_First_name', models.CharField(max_length=30)),
                ('Passenger_Last_name', models.CharField(max_length=20)),
                ('Passenger_Email_Id', models.CharField(max_length=30)),
                ('Passenger_Mobile_Number', models.CharField(max_length=10)),
                ('Passenger_Health_Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight_service.flight')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.fields.CharField, to='flight_service.passenger')),
            ],
        ),
    ]
